services:
  console.generator:
    class: SlytherinCz\SlyGen\Command\GeneratorCommand
    arguments:
      - "@factory.schema_factory"
      - "@service.generator.credentials"
      - "@service.generator.services"
      - "@service.generator.migration"
      - "@service.generator.controller"
      - "@service.generator.controller_di"
      - "@service.generator.model"
      - "@service.generator.routing"
      - "@service.generator.bootstrap"
      - "@service.generator.entrypoint"
      - "@service.file_writer"

  factory.primary_key_index:
    class: SlytherinCz\SlyGen\Factories\PrimaryKeyIndexFactory

  factory.foreign_key_index:
    class: SlytherinCz\SlyGen\Factories\ForeignKeyIndexFactory

  factory.unique_index:
    class: SlytherinCz\SlyGen\Factories\UniqueIndexFactory

  factory.index_factory:
    class: SlytherinCz\SlyGen\Factories\IndexFactory
    arguments:
      q:
       - "@factory.primary_key_index"
       - "@factory.foreign_key_index"
       - "@factory.unique_index"

  factory.schema_factory:
    class: SlytherinCz\SlyGen\Factories\SchemaFactory
    arguments:
        - "@factory.resource_collection_factory"

  factory.relation_collection_factory:
      class: SlytherinCz\SlyGen\Factories\RelationCollectionFactory
      arguments:
        - "@factory.relation_factory"

  factory.relation_factory:
      class: SlytherinCz\SlyGen\Factories\RelationFactory

  factory.resource_collection_factory:
    class: SlytherinCz\SlyGen\Factories\ResourceCollectionFactory
    arguments:
      - "@factory.resource_factory"

  factory.resource_factory:
    class: SlytherinCz\SlyGen\Factories\ResourceFactory
    arguments:
      - "@factory.column_collection_factory"
      - "@factory.index_collection_factory"
      - "@factory.option_collection_factory"
      - "@factory.relation_collection_factory"

  factory.option_collection_factory:
      class: SlytherinCz\SlyGen\Factories\OptionCollectionFactory
      arguments:
        - "@factory.option_factory"

  factory.option_factory:
    class: SlytherinCz\SlyGen\Factories\OptionFactory

  factory.column_collection_factory:
    class: SlytherinCz\SlyGen\Factories\ColumnCollectionFactory
    arguments:
      - "@factory.column_factory"

  factory.index_collection_factory:
    class: SlytherinCz\SlyGen\Factories\IndexCollectionFactory
    arguments:
      - "@factory.index_factory"

  factory.column_factory:
    class: SlytherinCz\SlyGen\Factories\ColumnFactory

  service.twig_loader:
    class: Twig_Loader_Filesystem
    arguments:
      "q":
        - "src/Templates"
        - "src/Templates/Dependency"
        - "src/Templates/Migration"
        - "src/Templates/Controller"
        - "src/Templates/Model"
        - "src/Templates/Command"

  service.twig_debug:
    class: Twig_Extension_Debug

  service.twig:
    class: Twig_Environment
    arguments:
      - "@service.twig_loader"
    calls:
      - method: addExtension
        arguments:
        - "@service.twig_debug"

  service.file_writer:
    class: SlytherinCz\SlyGen\Services\FileWriter

  service.generator.controller_di:
    class: SlytherinCz\SlyGen\Services\DependencyGenerator\ControllersDIGenerator
    arguments:
          - "@service.twig"

  service.generator.entrypoint:
    class: SlytherinCz\SlyGen\Services\EntrypointGenerator
    arguments:
        - "@service.twig"

  service.generator.credentials:
      class: SlytherinCz\SlyGen\Services\DependencyGenerator\CredentialsGenerator
      arguments:
        - "@service.twig"

  service.generator.routing:
        class: SlytherinCz\SlyGen\Services\DependencyGenerator\RoutingGenerator
        arguments:
          - "@service.twig"

  service.generator.migration:
        class: SlytherinCz\SlyGen\Services\MigrationGenerator
        arguments:
          - "@service.twig"

  service.generator.bootstrap:
          class: SlytherinCz\SlyGen\Services\BootstrapGenerator
          arguments:
            - "@service.twig"

  service.generator.controller:
        class: SlytherinCz\SlyGen\Services\ControllerGenerator
        arguments:
          - "@service.twig"

  service.generator.model:
         class: SlytherinCz\SlyGen\Services\ModelGenerator
         arguments:
           - "@service.twig"
           - "@service.relation_method_factory"

  service.generator.services:
        class: SlytherinCz\SlyGen\Services\DependencyGenerator\ServicesGenerator
        arguments:
          - "@service.twig"

  service.relation.one_to_many_relation_factory:
        class: SlytherinCz\SlyGen\Factories\RelationMethod\OneToManyRelationMethodFactory
        arguments:
            - "@service.twig"

  service.relation.many_to_one_relation_factory:
        class: SlytherinCz\SlyGen\Factories\RelationMethod\ManyToOneRelationMethodFactory
        arguments:
            - "@service.twig"

  service.relation_method_factory:
        class: SlytherinCz\SlyGen\Factories\RelationMethod\RelationMethodFactory
        calls:
          - method: add
            arguments:
              "q":
                - "@service.relation.one_to_many_relation_factory"
                - "@service.relation.many_to_one_relation_factory"
