services:
  console.generator:
    class: SlytherinCz\SlyGen\Command\GeneratorCommand
    arguments:
      - "@factory.schemaFactory"
      - "@service.generator.credentials"
      - "@service.generator.services"
      - "@service.fileWriter"

  factory.primaryKey:
    class: SlytherinCz\SlyGen\Factories\PrimaryKeyIndexFactory

  factory.indexFactory:
    class: SlytherinCz\SlyGen\Factories\IndexFactory
    arguments:
      q:
       - "@factory.primaryKey"

  factory.schemaFactory:
    class: SlytherinCz\SlyGen\Factories\SchemaFactory
    arguments:
        - "@factory.resourceCollectionFactory"

  factory.resourceCollectionFactory:
    class: SlytherinCz\SlyGen\Factories\ResourceCollectionFactory
    arguments:
      - "@factory.resourceFactory"

  factory.resourceFactory:
    class: SlytherinCz\SlyGen\Factories\ResourceFactory
    arguments:
      - "@factory.columnCollectionFactory"
      - "@factory.indexCollectionFactory"

  factory.columnCollectionFactory:
    class: SlytherinCz\SlyGen\Factories\ColumnCollectionFactory
    arguments:
      - "@factory.columnFactory"

  factory.indexCollectionFactory:
    class: SlytherinCz\SlyGen\Factories\IndexCollectionFactory
    arguments:
      - "@factory.indexFactory"

  factory.columnFactory:
    class: SlytherinCz\SlyGen\Factories\ColumnFactory

  service.twigLoader:
    class: Twig_Loader_Filesystem
    arguments:
      - "src/Templates"
    calls:
      - method: addPath
        arguments:
         - "src/Templates/Dependency"

  service.twig:
    class: Twig_Environment
    arguments:
      - "@service.twigLoader"

  service.fileWriter:
    class: SlytherinCz\SlyGen\Services\FileWriter

  service.generator.bootstrap:
    class: SlytherinCz\SlyGen\Services\BootstrapGenerator
    arguments:
      - "@service.twig"

  service.generator.credentials:
      class: SlytherinCz\SlyGen\Services\DependencyGenerator\CredentialsGenerator
      arguments:
        - "@service.twig"

  service.generator.services:
        class: SlytherinCz\SlyGen\Services\DependencyGenerator\ServicesGenerator
        arguments:
          - "@service.twig"
