services:
  console.generator:
    class: SlytherinCz\SlyGen\Command\GeneratorCommand
    arguments:
      - "@factory.schemaFactory"
      - "@service.generator.credentials"
      - "@service.generator.services"
      - "@service.generator.migration"
      - "@service.fileWriter"

  factory.primaryKeyIndex:
    class: SlytherinCz\SlyGen\Factories\PrimaryKeyIndexFactory

  factory.foreignKeyIndex:
    class: SlytherinCz\SlyGen\Factories\ForeignKeyIndexFactory

  factory.uniqueIndex:
    class: SlytherinCz\SlyGen\Factories\UniqueIndexFactory

  factory.indexFactory:
    class: SlytherinCz\SlyGen\Factories\IndexFactory
    arguments:
      q:
       - "@factory.primaryKeyIndex"
       - "@factory.foreignKeyIndex"
       - "@factory.uniqueIndex"

  factory.schemaFactory:
    class: SlytherinCz\SlyGen\Factories\SchemaFactory
    arguments:
        - "@factory.resourceCollectionFactory"

  factory.resourceCollectionFactory:
    class: SlytherinCz\SlyGen\Factories\ResourceCollectionFactory
    arguments:
      - "@factory.resourceFactory"

  factory.resourceFactory:
    class: SlytherinCz\SlyGen\Factories\ResourceFactory
    arguments:
      - "@factory.columnCollectionFactory"
      - "@factory.indexCollectionFactory"
      - "@factory.optionCollectionFactory"

  factory.optionCollectionFactory:
      class: SlytherinCz\SlyGen\Factories\OptionCollectionFactory
      arguments:
        - "@factory.optionFactory"

  factory.optionFactory:
    class: SlytherinCz\SlyGen\Factories\OptionFactory

  factory.columnCollectionFactory:
    class: SlytherinCz\SlyGen\Factories\ColumnCollectionFactory
    arguments:
      - "@factory.columnFactory"

  factory.indexCollectionFactory:
    class: SlytherinCz\SlyGen\Factories\IndexCollectionFactory
    arguments:
      - "@factory.indexFactory"

  factory.columnFactory:
    class: SlytherinCz\SlyGen\Factories\ColumnFactory

  service.twigLoader:
    class: Twig_Loader_Filesystem
    arguments:
      "q":
        - "src/Templates"
        - "src/Templates/Dependency"
        - "src/Templates/Migration"

  service.twigDebug:
    class: Twig_Extension_Debug

  service.twig:
    class: Twig_Environment
    arguments:
      - "@service.twigLoader"
    calls:
      - method: addExtension
        arguments:
        - "@service.twigDebug"

  service.fileWriter:
    class: SlytherinCz\SlyGen\Services\FileWriter

  service.generator.bootstrap:
    class: SlytherinCz\SlyGen\Services\BootstrapGenerator
    arguments:
      - "@service.twig"

  service.generator.credentials:
      class: SlytherinCz\SlyGen\Services\DependencyGenerator\CredentialsGenerator
      arguments:
        - "@service.twig"

  service.generator.migration:
        class: SlytherinCz\SlyGen\Services\MigrationGenerator
        arguments:
          - "@service.twig"

  service.generator.services:
        class: SlytherinCz\SlyGen\Services\DependencyGenerator\ServicesGenerator
        arguments:
          - "@service.twig"
